### ISSUE TITLE
examples for remote appenders

### ISSUE THREAD

**Issue by logemann** [hpoul/dart_logging_appenders#1]
Dont you think it would be a good idea to at least provide one example for each remote appender?

**Comment by logemann** [comment]
So i figured it out the hard way by reading code:

```
LogzIoApiAppender(
    apiToken: "ACCOUNT_TOKEN_FROM_USER",
    url: "https://listener-nl.logz.io:8071/",
    labels: {"myKey": "myVal"},
  )..attachToLogger(Logger.root);
```

Depending on the region you have chosen on account creation on logz.io, the following URLs are available and they really need to match otherwise you get a 401.

listener.logz.io — US East (Northern Virginia), AWS
listener-au.logz.io — Asia Pacific (Sydney), AWS
listener-ca.logz.io — Canada (Central), AWS
listener-eu.logz.io — Europe (Frankfurt), AWS
listener-nl.logz.io — West Europe (Netherlands), Azure
listener-wa.logz.io — West US 2 (Washington), Azure

**Comment by hpoul** [comment]
thanks for the reminder.. i'll add the documentation.. but i think the URLs are exactly the same as you would configure for any other logz.io provider.
where did you find that list of urls, btw? :-)

**Comment by logemann** [comment]
the list of urls i got from the support staff at logz.io ... btw, tomorrow (the day after tomorrow latest) i will finish my medium article about logz.io and your appender. Will post it here... perhaps you want to link it or something...

**Comment by hpoul** [comment]
i've now added a very trivial example: https://github.com/hpoul/dart_logging_appenders/blob/master/README.md#appender-for-logzio
sure, let me know once it's up and i'll take a look, thanks.

**Comment by logemann** [comment]
https://medium.com/saas-startup-factory/remote-logging-with-flutter-on-the-logz-io-elk-stack-f360df143ef0
