### ISSUE TITLE
Detailed example for Rotating File Logger with multiple log files.

### ISSUE THREAD

**Issue by ishaantantra** [hpoul/dart_logging_appenders#11]
Can you provide a detailed example for Rotating File Logger with multiple log files i.e. error, info and warning are stored in different log files (error.log, info.log and warning.log).

keepRotateCount = 3
rotateAtSizeBytes = 100 * 1024 * 1024 //100.M.B.

**Comment by hpoul** [comment]
What issue did you encounter when configuring your loggers? If you can point to any problems i might be able to help. I don't really have time right now, if you want, feel free to contribute some documentation. Other than that i can't quite find any issues to since here.
