### ISSUE TITLE
Support dio 5

### ISSUE THREAD

**Issue by dokkaebi** [hpoul/dart_logging_appenders#17]
Dio has been updated to 5.0, and now version solving fails:

`Because logging_appenders 1.0.0+2 depends on dio ^4.0.0 and no versions of logging_appenders match >1.0.0+2 <2.0.0, logging_appenders ^1.0.0+2 requires dio ^4.0.0.`

**Comment by hpoul** [comment]
should be fixedin 1.0.1 now.. I don't think there were any breaking changes

**Comment by dokkaebi** [comment]
Looks good to me, thanks!
