### ISSUE TITLE
RotatingFileAppender is broken on Windows

### ISSUE THREAD

**Issue by Markus43** [hpoul/dart_logging_appenders#18]
Hi,

first of all, thanks for this library!

When using the RotatingFileAppender in my Windows Desktop app, I get an exception as soon as the file rotation happens. This is because the code tries to rename a file that is still open, which is not allowed on Windows.

There already is a PR #15 that fixes the issue for me, I tried with the forked version from that PR and then the file rotation worked for me.

Would be really nice to get that PR (or something similar) released :-) I'd also be willing to test any possible bugfix.

**Comment by hpoul** [comment]
hi,
thanks of the reminder.. i've just published 1.0.2
