### ISSUE TITLE
SimpleJobQueue does not clear queue

### ISSUE THREAD

**Issue by CatAndLion** [hpoul/dart_logging_appenders#19]
I have notices that BaseLogSender does not clear internal _sendQueue correctly.
My suggestion this is because this lines (base_remote_appender.dart):
https://github.com/hpoul/dart_logging_appenders/blob/4898a9ec5a98446f5508dfc13981b6f89dcc0f56/lib/src/remote/base_remote_appender.dart#L180-L187
listen method expects that _currentStream yields SimpleJobDef but in fact it returns Future<SimpleJobDef>
and _queue does not changes.

**Comment by hpoul** [comment]
can't reproduce that problem.. maybe you can adopt the test to fail: https://github.com/hpoul/dart_logging_appenders/blob/master/test/simple_job_queue_test.dart
